# Generated by Django 4.2.3 on 2023-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=205)),
                ('age', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
