# Generated by Django 4.2.3 on 2023-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='enrolledStudents',
            field=models.IntegerField(default=0),
        ),
    ]
